### ISSUE TITLE
What organisms is this designed for?

### ISSUE THREAD

**Issue by tseemann** [Plant-Food-Research-Open/assemblyqc#124]
### Description of feature

It is unclear if this pipeline will work on any organism assembly?

Is it haploid genomes only?
Is it especially for bacteria?

**Comment by GallVp** [comment]
Hi @tseemann 

At Plant&Food we have been using the pipeline to QC genomes of plants, animals, and fungi. It was also tested with a bacterial genome.

We have also used it on diploid genomes. The two haplotypes can be processed in parallel by inputting them as two `fasta` files.
