### ISSUE TITLE
Add gfastats

### ISSUE THREAD

**Issue by GallVp** [Plant-Food-Research-Open/assemblyqc#126]
### Description of feature

- https://github.com/vgl-hub/gfastats

**Comment by GallVp** [comment]
Some of the gap statistics are missing from ASSEMBLATHON STATS such as,

# gaps in scaffolds: 0
Total gap length in scaffolds: 0
Average gap length in scaffolds: 0.00
Gap N50 in scaffolds: 0
Gap auN in scaffolds: 0.00
Gap L50 in scaffolds: 0
Largest gap in scaffolds: 0
Smallest gap in scaffolds: 0

**Comment by christinawu2008** [comment]
This is required for red assemblies, AWS testing...
