### ISSUE TITLE
Parameter validation failed for --hic

### ISSUE THREAD

**Issue by GallVp** [Plant-Food-Research-Open/assemblyqc#179]
### Description of the bug

ERROR ~ Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
The following invalid input values have been detected:

* --hic (SB1031HiC1.fastq.gz): "SB1031HiC1.fastq.gz" does not match regular expression [^SR\w+$|^\S+\{1,2\}[\w\.]*\.f(ast)?q\.gz$]

### Command used and terminal output

```console
nextflow run plant-food-research-open/assemblyqc \
-revision 2.2.0  \
-profile singularity \
--hic SB1031HiC{1,2}.fastq.gz
```

### System information

plant-food-research-open/assemblyqc -revision 2.2.0

**Comment by GallVp** [comment]
This issue arises from the bash expansion operator `{}`. Bash can be stopped from expanding the HiC files by wrapping it in double quotes as,

`—hic "SB1031HiC{1,2}.fastq.gz”`

Otherwise, the pipeline sees the following input,

`—hic SB1031HiC1.fastq.gz SB1031HiC2.fastq.gz`

and the trouble with Nextflow is that it does not pick up multiple arguments for one parameter.

**Comment by annabel-NZ** [comment]
Although this solution fixes the initial input validation step, I am still failing to get the pipeline to treat the HiC input as I would like. The fastq files are in the local directory (but as sym links) The pipeline is failing and seems to be attempting to source these inputs from SRA. 
```
ERROR ~ Error executing process > 'PLANTFOODRESEARCHOPEN_ASSEMBLYQC:ASSEMBLYQC:FETCHNGS:SRATOOLS_PREFETCH (SB1031HiC{1,2}.fastq.gz)'

Caused by:
  Process `PLANTFOODRESEARCHOPEN_ASSEMBLYQC:ASSEMBLYQC:FETCHNGS:SRATOOLS_PREFETCH (SB1031HiC{1,2}.fastq.gz)` terminated with an error exit status (1)
```

**Comment by GallVp** [comment]
Thank you @annabel-NZ 

This is a bug in the pipeline logic unfortunately due to the following logic,

https://github.com/Plant-Food-Research-Open/assemblyqc/blob/01419251d52a057caa8fda571704ddc468be10d3/subworkflows/local/utils_nfcore_assemblyqc_pipeline/main.nf#L89

It expects that the fastq files will be nested under some path. To get around this, please try,

```bash
--hic "./SB1031HiC{1,2}.fastq.gz”
```

as the files are in the current directory (`./`). I'll try to fix it in the next update.
