### ISSUE TITLE
Adapter screen for long sequencing adaptors

### ISSUE THREAD

**Issue by rosscrowhurst** [Plant-Food-Research-Open/assemblyqc#55]
Current fcs is for short read (Roche 454, ABI Solid and Illumina). Need to augment with screens for PacBio adapters (eg smartbell),, ONT adapters etc

**Comment by GallVp** [comment]
NCBI FCS Adaptor screen has been updated to include PacBio and NanoPore adapters: https://github.com/ncbi/fcs/releases/tag/v0.5.0

**Comment by GallVp** [comment]
Hi @ignacio3437, @SarahBailey1998

Can you kindly suggest a few PacBio adapters? Can you kindly also share the workflow using minimap2 to detect the adapters?

Many Thanks

**Comment by ignacio3437** [comment]
See Fig1  of the sup materials here for how the Human Pangenome team dealt with contamination:
https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-023-05896-x/MediaObjects/41586_2023_5896_MOESM1_ESM.pdf

The code is here:
https://github.com/sheinasim/HiFiAdapterFilt/tree/master
with the seqs here:
https://github.com/sheinasim/HiFiAdapterFilt/blob/master/DB/pacbio_vectors_db

I also found this repo from the Tree of Life project that lists some more PacBio Adaptor seqs and barcodes but the base adaptor is the same sequence in both files:
https://github.com/sanger-tol/vectorDB/blob/main/pacbio_vectorDB.fasta

**Comment by GallVp** [comment]
Thank you @ignacio3437 

That's very useful. I have tested the ability of the latest fcs/fcsadaptor to detect PacBio adapters and it is able to detect them. See the test here: https://github.com/nf-core/modules/blob/322e9e62e6435bdfbc862a5083856f1cb2192002/modules/nf-core/fcs/fcsadaptor/tests/main.nf.test#L47-L77

The updated fcs/fcsadaptor will be added to the pipeline as part of the next release.
