### ISSUE TITLE
Duplication checks

### ISSUE THREAD

**Issue by GallVp** [Plant-Food-Research-Open/assemblyqc#64]
From @CeciliaDeng 

BTW, we haven't checked duplicate sequences in assembly, have we? I can't remember if the QC pipeline checks for mitochondria/plastids/ribosomal rna contaminations. If not, we may list them as 'todo for future release'?

**Comment by GallVp** [comment]
Hi @CeciliaDeng 

Does the above comment from Ross answer your question? Is there a tool you have in mind for duplicate detection?

**Comment by CeciliaDeng** [comment]
Hi @GallVp and @rosscrowhurst, We encountered duplicated sequences before in our NCBI submission, in particular de novo assemblies from short reads. Yes, the duplicated seqs are usually at contig level, with exactly the same sequence but different SeqIDs. I ran 'ml seqkit; seqkit rmdup -s -o $checkedFasta $inputFasta' to remove such items

**Comment by CeciliaDeng** [comment]
For genomes we downloaded from public domain, sometimes there exists duplicated seqIDs and 'samtools faidx $inputFasta' will complain and exit. In that case we can use 'seqkit rmdup -n -o $outFile $inputFasta' to remove seqs with the same ID. However their sequences could be different even with the same SeqID, in that case I usually append '.1', '.2' and so on for the sequences with the same ID.

**Comment by GallVp** [comment]
We are using py_fasta_validator to validate `fasta` files. It does detect sequence ID duplication. Please see:

https://github.com/linsalrob/py_fasta_validator/blob/32d1d2a49da550df41d44bc61be4341cdf104ae4/PyFastaValidator/validate.py#L28
