### ISSUE TITLE
https://github.com/schneebergerlab/plotsr

### ISSUE THREAD

**Issue by GallVp** [Plant-Food-Research-Open/assemblyqc#77]

**Comment by GallVp** [comment]
[4:20 pm] Ross Crowhurst
I wouldn't rush to add it since it requires all chromosomes in both genomes to be exact same orientation (and that is never guaranteed so has to be fixed before use in nucmer - most tools do not care - this one doses). It also requires each genome to have same number of chromosomes and not include any contigs. It also requires names to be same eg 'Chr01' as name in both. It also only handles a single genome sequence from each genome and not haplotypes. If haplotypes than each one has to be done pairwise vs all others - so a checker board. So it might be more trouble to add to pipelines than its worth

**Comment by GallVp** [comment]
@rosscrowhurst

**Comment by rosscrowhurst** [comment]
See https://github.com/schneebergerlab/plotsr for multi-genome (but pairwise) workflow

**Comment by GallVp** [comment]
Hi @rosscrowhurst 

Is this needed after the addition of the linear synteny plot in addition to the circos plot? As you have mentioned in your previous message, it also requires stringent naming convention among other issues.

**Comment by rosscrowhurst** [comment]
plotsr has recently been used by others now - for example Sarah Bailey recently used it. IT does a nicer job of displaying inversions, duplications, deletions etc. so it has two foci - one is during assembly to check haplotype assemblies against each other (for example) and one at the end of the assembly to see the differences better between your genome and another. But I am wondering if it needs to be part of assemblyqc automatically as you could not use it unless you had a second genome (say 2 haplotypes) so it would be an optional module at most

**Comment by GallVp** [comment]
Hi @rosscrowhurst 

I have added PLOTSR to the dev branch. I'll be testing the pipeline before creating a release. In case you need early access to it, please download the `dev` branch and try it.
